version: '3.3'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:8080
    depends_on:
      - backend
  backend:
    build: .
    ports:
    - 5000:8080
    volumes:
      - ./output:/output
    environment:
      - LISTEN=:8080
      - LOG_LEVEL=debug
      - IND_FILE=final.csv
