version: '3.3'

services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - elasticsearch
    ports:
      - 24224:24224
      - 24224:24224/udp
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
    expose:
      - 9200
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.2.0
    links:
      - elasticsearch
    ports:
      - 5601:5601