version: '3.3'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:8080
    depends_on:
      - backend
    links:
      - backend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.log

  backend:
    build: .
    environment:
      - LOG_LEVEL=debug
      - IND_FILE=final.csv
      - IND_FOLDER=./output
      - PORT=8080
      - LISTEN=:${PORT}
    ports:
    - 8080:$(PORT)
    volumes:
      - ${IND_FOLDER}:/output
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: backend.log



