version: '3.3'

services:
  nginx:
    build: ./nginx
    image: search-senyast4745/nginx:latest
    ports:
      - 80:8080
    depends_on:
      - backend
  #    logging:
  #      driver: "fluentd"
  #      options:
  #        fluentd-address: localhost:24224
  #        tag: nginx.log

  building:
    build: .
    image: polisgo2020/search-senyast4745/searchind:latest
    environment:
      - LOG_LEVEL=debug
      - LISTEN=:8080
      - DATABASE
      - DB_INTERFACE
    ports:
      - 8082:8080
    volumes:
      - ./output:/output
      - ./data:/data
    entrypoint: /app/app build -s /data
    depends_on:
      - mongo


  search:
    image: polisgo2020/search-senyast4745/searchind:latest
    environment:
      - LOG_LEVEL=debug
      - LISTEN=:8080
      - DATABASE
      - DB_INTERFACE
    ports:
      - 8080:8080
    volumes:
      - ./output:/output
    entrypoint: /app/app search
    depends_on:
      - building


  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mongo/data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
    depends_on:
      - mongo



