version: '3.3'

services:
  nginx:
    build: ./nginx
    image: search-senyast4745/nginx:latest
    ports:
      - 80:8080
    depends_on:
      - backend
    links:
      - backend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.log

  backend:
    build: .
    image: search-senyast4745/search:latest
    environment:
      - LOG_LEVEL=debug
      - IND_FILE=final.csv
      - LISTEN=:8080
    ports:
      - 8080:8080
    volumes:
      - ./output:/output
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: backend.log


